version: 2.1

workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
      - job04:
          requires:
            - test            
            

jobs:
  build:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run: 
          name: Checking Node Version
          command: node --version
      - run: 
          name: Moving to App Directory
          command: cd app && ls -l
      - run:
          name: Install Dependencies
          command: pwd && cd app && npm install
      - run:
          name: Running App
          command: cd app && echo "Done" #npm run start
      - run: echo "Bye"
      
  test:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run: 
          name: Checking Node Version
          command: node --version
          
  deploy:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run: |
          echo "Testing if Deployment step is working"
          echo "Testing 1 2 3..."
          date
          echo "Testing Completed"
    
    
  job04:
    docker:
      - image: cimg/base:2021.11
    steps:
      - run: 
          name: "Triggeting Job04"
          command: |
            echo "Testing if Deployment step is working"
            echo "Testing 1 2 3..."
            date
            echo "Testing Completed"    
        
