version: 2.1

workflows:
  build-test:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run: 
          name: Checking Node Version
          command: node --version
      - run: 
          name: Moving to App Directory
          command: cd app && ls -l
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Running App
          command: npm run start
      - run: echo "Bye"
        
